### ISSUE TITLE
🛑 Anduin App Deal main page is down

### ISSUE THREAD

**Issue by cmpham** [anduintransaction/upptime#402]
In [`4245bcf`](https://github.com/anduintransaction/upptime/commit/4245bcf28ffa89f8117789ef9357bf148f93e0ef
), Anduin App Deal main page (https://deals.anduin.app/) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by msongd** [comment]
Wrong status page url, should be deals.anduintransact.com. Fixed.
