### ISSUE TITLE
🛑 Anduin App Deal status is down

### ISSUE THREAD

**Issue by cmpham** [anduintransaction/upptime#476]
In [`4e548b7`](https://github.com/anduintransaction/upptime/commit/4e548b7f3187f893162eb6a5b34431c3faa733ea
), Anduin App Deal status (https://deals.anduintransact.com/api/v2/standalone-app/get-app-version) was **down**:
- HTTP code: 404
- Response time: 90 ms

**Comment by msongd** [comment]
back to normal
