### ISSUE TITLE
🛑 Anduin App Dataroom status is down

### ISSUE THREAD

**Issue by cmpham** [anduintransaction/upptime#477]
In [`168e003`](https://github.com/anduintransaction/upptime/commit/168e003f0447110fff8158b953ea33176483a1d1
), Anduin App Dataroom status (https://dataroom.anduin.app/api/v2/standalone-app/get-app-version) was **down**:
- HTTP code: 404
- Response time: 65 ms

**Comment by msongd** [comment]
back to normal
