### ISSUE TITLE
🛑 Anduin App Sign status is down

### ISSUE THREAD

**Issue by cmpham** [anduintransaction/upptime#478]
In [`5787049`](https://github.com/anduintransaction/upptime/commit/57870499c60bb6e4ba83c7658d5a4da7d0df2b70
), Anduin App Sign status (https://sign.anduin.app/api/v2/standalone-app/get-app-version) was **down**:
- HTTP code: 404
- Response time: 95 ms

**Comment by msongd** [comment]
back to normal
