### ISSUE TITLE
🛑 SyncGateway Gondor Canary is down

### ISSUE THREAD

**Issue by msongd** [anduintransaction/upptime#564]
In [`4441977`](https://github.com/anduintransaction/upptime/commit/4441977c7bbcf5fa66133184d0d94547d483e0f7
), SyncGateway Gondor Canary ($SYNCGATEWAY_CANARY_ANDUINTRANSACT) was **down**:
- HTTP code: 404
- Response time: 78 ms

**Comment by victorle-sec** [comment]
Not used anymore, remove from monitoring
