### ISSUE TITLE
🛑 SyncGateway Minas Tirith is down

### ISSUE THREAD

**Issue by msongd** [anduintransaction/upptime#565]
In [`b165875`](https://github.com/anduintransaction/upptime/commit/b165875acd55c247e88038913886298510354bef
), SyncGateway Minas Tirith ($SYNCGATEWAY_MINAS_ANDUINTRANSACT) was **down**:
- HTTP code: 404
- Response time: 66 ms

**Comment by victorle-sec** [comment]
Not used anymore, remove from monitoring
