### ISSUE TITLE
🛑 SyncGateway Gondor Internal is down

### ISSUE THREAD

**Issue by msongd** [anduintransaction/upptime#567]
In [`b66a65d`](https://github.com/anduintransaction/upptime/commit/b66a65d70078be672e6be514b2c303031dd3b850
), SyncGateway Gondor Internal ($SYNCGATEWAY_INTERNAL_ANDUINTRANSACT) was **down**:
- HTTP code: 404
- Response time: 145 ms

**Comment by victorle-sec** [comment]
Not used anymore, remove from monitoring

**Comment by victorle-sec** [comment]
Not used anymore, remove from monitoring
